-- phpMyAdmin SQL Dump
-- version 5.1.3
-- https://www.phpmyadmin.net/
--
-- Host: mysql
-- Generation Time: Feb 21, 2023 at 01:30 PM
-- Server version: 10.8.6-MariaDB-1:10.8.6+maria~ubu2204-log
-- PHP Version: 7.2.34

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `anime_viewer`
--

-- --------------------------------------------------------

--
-- Table structure for table `Anime`
--

CREATE TABLE `Anime` (
  `id` int(11) NOT NULL,
  `Name` varchar(500) DEFAULT NULL,
  `Day` varchar(255) DEFAULT NULL,
  `Description` longtext DEFAULT NULL,
  `Image` varchar(255) DEFAULT NULL,
  `Url` varchar(255) DEFAULT NULL,
  `MalID` int(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `Anime`
--

INSERT INTO `Anime` (`id`, `Name`, `Day`, `Description`, `Image`, `Url`, `MalID`) VALUES
(1, 'In/Spectre 2', 'Mondays', 'During a blizzard, Masayuki Muroi\'s old high school friend pushes him off a mountain to certain death. However, Masayuki survives the fall and escapes to safety thanks to Yuki-Onna, the spirit of a beautiful young woman who is said to lead men to their demise—but all she asks in return is money.\n\nEleven years later, Masayuki has lived a successful life, having gotten married and amassing a great fortune. But when his company collapses and his wife cheats on him, Masayuki retreats to the city where Yuki-Onna once saved him, and he reconnects with her by offering her money and tasty meals. While Masayuki recovers from his misfortunes, another one knocks on his door: his ex-wife is found beaten to death, and now only Yuki-Onna—who cannot reveal herself—can corroborate his alibi.\n\nWith no one to turn to, Yuki-Onna enlists the help of the spirits\' God of Wisdom, Kotoko Iwanaga. Revered by the various spirits that wander the earth, Kotoko uses her extraordinary wits and cunning to solve all quarrels they may have. In her duty to protect spirits and humans from colliding, Kotoko drags along her immortal boyfriend, Kurou Sakuragawa, and promises to prove Masayuki\'s innocence without exposing Yuki-Onna\'s existence.\n\n[Written by MAL Rewrite]', 'https://cdn.myanimelist.net/images/anime/1901/131653.jpg', 'https://myanimelist.net/anime/44204/Kyokou_Suiri_Season_2', 44204),
(2, 'Vinland Saga Season 2', 'Tuesdays', 'After his father\'s death and the destruction of his village at the hands of English raiders, Einar wishes for a peaceful life with his family on their newly rebuilt farms. However, fate has other plans: his village is invaded once again. Einar watches helplessly as the marauding Danes burn his lands and slaughter his family. The invaders capture Einar and take him back to Denmark as a slave. \n\nEinar clings to his mother\'s final words to survive. He is purchased by Ketil, a kind slave owner and landlord who promises that Einar can regain his freedom in return for working in the fields. Soon, Einar encounters his new partner in farm cultivation—Thorfinn, a dejected and melancholic slave. As Einar and Thorfinn work together toward their freedom, they are haunted by both sins of the past and the ploys of the present. Yet they carry on, grasping for a glimmer of hope, redemption, and peace in a world that is nothing but unjust and unforgiving.\n\n[Written by MAL Rewrite]', 'https://cdn.myanimelist.net/images/anime/1170/124312.jpg', 'https://myanimelist.net/anime/49387/Vinland_Saga_Season_2', 49387),
(3, 'Kubo Won\'t Let Me Be Invisible', 'Tuesdays', 'Junta Shiraishi is a high school student with one simple goal—to enjoy his youth. However, achieving this goal is not so straightforward since Shiraishi is effectively invisible to his peers; even his teachers routinely fail to notice his presence. In fact, there is a rumor circulating that whoever manages to spot him will receive good luck. \n\nBut there is one person who notices Shiraishi\'s presence without fail. Seated right next to him, Nagisa Kubo is determined not to let him quietly fade into the background. Unfortunately for him, this means that Shiraishi finds himself in some peculiar situations, all orchestrated by Kubo. Despite this, Kubo\'s playful antics might just be the catalyst needed to spark the thrilling youth that Shiraishi longs for.\n\n[Written by MAL Rewrite]', 'https://cdn.myanimelist.net/images/anime/1818/132330.jpg', 'https://myanimelist.net/anime/51815/Kubo-san_wa_Mob_wo_Yurusanai', 51815),
(4, 'Reborn to Master the Blade: From Hero-King to Extraordinary Squire ♀', 'Tuesdays', 'The hero king Inglis—who dedicated his entire life to building his country—is now approaching death. To award him for his honorable achievements, the goddess Alistia appears and grants him one wish. Having never been able to master the blade, Inglis asks to be reincarnated in order to do so.\n\nIn a blink of an eye, Inglis finds himself born in the far future as a daughter of the Eucus noble family. Six years later, Inglis is discovered to be Runeless—incapable of utilizing the runes that enable the use of magic in this era. She is therefore ineligible to become a knight. However, this fits in well with Inglis\' plan: she instead decides to become the squire for her cousin, Rafinha Bilford, allowing Inglis to focus on pushing her limits.\n\nFor Inglis, the challenges this familiar yet different world has to offer are instead opportunities for her to hone her skills—and possibly become an extraordinary squire in the process.\n\n[Written by MAL Rewrite]', 'https://cdn.myanimelist.net/images/anime/1044/129594.jpg', 'https://myanimelist.net/anime/50481/Eiyuu-ou_Bu_wo_Kiwameru_Tame_Tenseisu__Soshite_Sekai_Saikyou_no_Minarai_Kishi♀', 50481),
(5, 'Ningen Fushin: Adventurers Who Don\'t Believe in Humanity Will Save the World', 'Tuesdays', 'Veteran adventurer Nick, mage Tiana, cleric Zem, and half-dragon Curran each show up alone at a tavern, only to find themselves seated at the same table. As the night goes on, they take turns divulging their grievances and the hobbies they have taken up as a means of coping. While their stories are utterly different, there is one common thread: betrayal. Each of the four, having been bitterly betrayed by someone they treasured, has developed a deep-seated distrust of humanity.\n\nBut in addition to their similar worldviews, the four have one more commonality: a critical lack of funds. Realizing that things cannot continue as they are, they decide to form a party, rank up, and make as much money as possible to spend on their respective hobbies. What these disillusioned adventurers do not know, however, is that they will one day save the world from unfathomable peril.\n\n[Written by MAL Rewrite]', 'https://cdn.myanimelist.net/images/anime/1446/131578.jpg', 'https://myanimelist.net/anime/49612/Ningen_Fushin_no_Boukensha-tachi_ga_Sekai_wo_Sukuu_you_desu', 49612),
(6, 'Campfire Cooking in Another World with My Absurd Skill', 'Wednesdays', 'Along with three other heroes, 27-year-old Mukouda Tsuyoshi is transported into a fantasy world to rescue a kingdom from a mysterious threat. However, it soon becomes clear that Tsuyoshi has been dragged into the summoning ritual by accident. His only skill turns out to be \"Food Menu,\" which allows him to open an interface where he can purchase and obtain food-related supermarket items from modern Japan.\n\nUnceremoniously booted out of the palace, Tsuyoshi sets out on his own into his new world. However, his ability to create delicious dishes unknown to this world soon pays dividends, even attracting the legendary wolf Fenrir. Fenrir is so taken in by the food that the creature immediately forms a contract with Tsuyoshi, becoming his familiar. Followed by this whimsical mythical being, Tsuyoshi takes up a job as a merchant and adventurer, travelling and cooking up mouth-watering meals that never fail to amaze the inhabitants of this world.\n\n[Written by MAL Rewrite]', 'https://cdn.myanimelist.net/images/anime/1661/131889.jpg', 'https://myanimelist.net/anime/53446/Tondemo_Skill_de_Isekai_Hourou_Meshi', 53446),
(7, 'The Magical Revolution of the Reincarnated Princess and the Genius Young Lady', 'Wednesdays', 'Princess Anisphia \"Anis\" Wynn Palletia has always dreamed of flying through the sky, even though the people of her kingdom consider it a silly ambition. Also at odds with her goal is the fact that Anis is incapable of using magic despite her noble status. Refusing to give up so easily, she renounces her right to the throne, and focuses on developing \"magicology\" by combining various resources with knowledge from her previous life on Earth.\n\nDue to Anis\' nature, responsibility for the kingdom\'s future is passed onto her younger brother, Algard. Pushed into a political marriage with Euphyllia Magenta, a girl he hardly knows, Algard rebels by spending more time with a commoner girl than his fiancée. After Euphyllia tries to intervene, Algard publicly calls off their marriage and denounces his ex-fiancée as a bully.\n\nAfter crashing into the banquet where Algard makes the announcement, Anis rescues Euphyllia on the flying broom she is testing. She decides to make Euphyllia her assistant, which the other girl reluctantly agrees to. Although their partnership appears random at first, Anis has an ulterior motive for wanting Euphyllia\'s company.\n\n[Written by MAL Rewrite]', 'https://cdn.myanimelist.net/images/anime/1053/129004.jpg', 'https://myanimelist.net/anime/52736/Tensei_Oujo_to_Tensai_Reijou_no_Mahou_Kakumei', 52736),
(8, 'Bungo Stray Dogs 4', 'Wednesdays', 'Fourth season of Bungou Stray Dogs.', 'https://cdn.myanimelist.net/images/anime/1263/132759.jpg', 'https://myanimelist.net/anime/50330/Bungou_Stray_Dogs_4th_Season', 50330),
(9, 'BOFURI: I Don\'t Want to Get Hurt, so I\'ll Max Out My Defense. Season 2', 'Wednesdays', 'After achieving fruitful results in New World Online\'s previous events, the now famous Maple Tree guild is excited to explore the new floors introduced in game. As if their guild was not already feared enough, each member is motivated to find stronger skills for themselves in order to greatly expand their options in future battles. Not forgetting the importance of networking, the guild also forges amicable relationships with other notable guilds, such as the Kingdom of the Flame Emperor and the Congregation of the Holy Swords.\n\nWith their eccentric guild master Maple at the forefront, the members of Maple Tree continue to stumble upon creative ways to implement their skills, driving the game developers crazy along the way.\n\n[Written by MAL Rewrite]', 'https://cdn.myanimelist.net/images/anime/1782/128859.jpg', 'https://myanimelist.net/anime/41514/Itai_no_wa_Iya_nano_de_Bougyoryoku_ni_Kyokufuri_Shitai_to_Omoimasu_2', 41514),
(10, 'The Ice Guy and His Cool Female Colleague', 'Wednesdays', 'Kind-hearted Himuro-kun is unfortunate: when in deep concentration, stressed, or flustered, he involuntarily creates blizzard conditions for himself and anyone in his vicinity. During one such incident on the first day of his new job, Himuro-kun encounters the beautiful Fuyutsuki-san, who helps him break out of his nerve-induced ice. As it turns out, Fuyutsuki-san is his new coworker.\n\nAt the office, the cool-headed Fuyutsuki-san offers simple and rational solutions to Himuro-kun\'s icy dilemmas—everything from helping him garden without freezing his plants to ensuring he does not melt during their tropical work retreat. Every time Fuyutsuki-san does something kind for him, the tempest of emotions he experiences inside embarrassingly manifests on the outside.\n\nAs a result of the frequent snowstorms, Himuro-kun\'s feelings for Fuyutsuki-san are impossible to hide. Even though Fuyutsuki-san is unfamiliar with love, Himuro-kun remains determined to repay her kindness and warm her heart in any way he can.\n\n[Written by MAL Rewrite]', 'https://cdn.myanimelist.net/images/anime/1927/132758.jpg', 'https://myanimelist.net/anime/52173/Koori_Zokusei_Danshi_to_Cool_na_Douryou_Joshi', 52173),
(11, 'Spy Classroom', 'Thursdays', 'A decade ago, mankind witnessed the deadly potential of weapons caused by the Great War. To avoid another catastrophe, governments worldwide have resorted to espionage to fulfill their agendas.\n\nIn the Din Republic, Lily is an enthusiastic young girl who aspires to become a spy and serve her nation. However, she begins to doubt her abilities, as she struggles to perform well academically. Lily\'s passion is reignited when she is offered provisional graduation by joining the spy team Lamplight, which she eagerly accepts despite the enigmatic nature of the opportunity.\n\nUpon arriving at her destination, Lily is surprised to find six other girls waiting there, all of whom have faced their own academic difficulties as well. A mysterious man named Klaus soon appears and reveals they must complete an \"Impossible Mission\": to infiltrate the Galgad Empire after just one month of training. Although skeptical, the girls eventually agree to work together under Klaus\' guidance—as this might be their only chance to prove their worth as spies.\n\n[Written by MAL Rewrite]', 'https://cdn.myanimelist.net/images/anime/1491/132864.jpg', 'https://myanimelist.net/anime/51252/Spy_Kyoushitsu', 51252),
(12, 'Onimai: I\'m Now Your Sister!', 'Thursdays', 'Self-professed \"home security guard\" Mahiro Oyama has not left his home in years, secluding himself in his room playing erotic visual novels. This depraved lifestyle causes his prodigious sister, Mihari, to worry about his well-being. In hopes of solving this problem, she devises a plan to rehabilitate him back to normalcy.\n\nThe first part of Mihari\'s plan is to concoct a medicine that changes her brother\'s biological constitution into a bona fide female, much to Mahiro\'s vehement dismay. Stuck in this predicament, Mahiro has no choice but to live out his life as a cute girl until the effect wears off—if it ever does.\n\n[Written by MAL Rewrite]', 'https://cdn.myanimelist.net/images/anime/1058/131632.jpg', 'https://myanimelist.net/anime/51678/Oniichan_wa_Oshimai', 51678),
(13, 'Tomo-chan Is a Girl!', 'Thursdays', 'Childhood friends Tomo Aizawa and Junichirou \"Jun\" Kubota do everything together, whether it be training or just enjoying a fun day out. Anyone would think that these two are best friends for life. The only issue is that the tomboyish Tomo is in love with Jun, but he regards her like a brother.\n\nAt the start of their first year of high school, Tomo confesses her feelings to Jun. However, her rough mannerisms and lack of hesitance to throw a punch do nothing to sway Jun\'s heart. Realizing that he will remain indifferent to her affections unless she does something about it, Tomo must find a way to knock some sense into Jun and open his eyes to what is right in front of him.\n\n[Written by MAL Rewrite]', 'https://cdn.myanimelist.net/images/anime/1444/131828.jpg', 'https://myanimelist.net/anime/52305/Tomo-chan_wa_Onnanoko', 52305),
(14, 'Farming Life in Another World', 'Fridays', 'During the final years of his life, Hiraku Machio remained confined to a hospital bed with a terminal illness until he finally passed away. Taking pity on the unfair life he lived, a god decides to reincarnate Hiraku in another world where he can live as he pleases. Wanting to try farming in this new life, he is bestowed with an all-in-one \"Almighty Farming Tool\" that can transform into any useful implement he wishes. Hiraku is then transported to a forest seemingly far from civilization. Here, he plans to build and farm everything from scratch—gradually developing the lifeless area into a thriving new society.\n\n[Written by MAL Rewrite]', 'https://cdn.myanimelist.net/images/anime/1983/132329.jpg', 'https://myanimelist.net/anime/51462/Isekai_Nonbiri_Nouka', 51462),
(15, 'The Iceblade Sorcerer Shall Rule the World', 'Fridays', 'As the first commoner to attend the prestigious Arnold Academy of Sorcery, Ray White is immediately met with contempt from some of the students hailing from nobility. Unbeknownst to them, Ray\'s real identity is that of the famous Iceblade Sorcerer—a hero who led the country to victory in a past war and is one of the seven strongest sorcerers alive. Despite his legendary status, Ray wants nothing more than to live out the ordinary school life he never had.\n\nRay quickly makes friends with some of the most influential students thanks to his kind and amiable nature. Unfortunately, as those with nefarious motives begin to make their move, Ray may soon have no choice but to use his true power to preserve the bonds that make his new life worthwhile.\n\n[Written by MAL Rewrite]', 'https://cdn.myanimelist.net/images/anime/1049/131580.jpg', 'https://myanimelist.net/anime/51711/Hyouken_no_Majutsushi_ga_Sekai_wo_Suberu', 51711),
(16, 'Buddy Daddies', 'Saturdays', 'On Christmas Eve, four-year-old Miri Unasaka arrives in Tokyo completely alone, in search of her father. The bright lights and merry atmosphere guide Miri to a big hotel and a man with a delicious-looking cake. However, the child has just unknowingly walked into the center of an elaborate, foolproof plan for assassinating a dangerous mafia boss.\n\nProfessional assassins Kazuki Kurusu and Rei Suwa live together, fleeing memories of their grim childhoods and avoiding emotional connections. When their mission goes awry and they end up bringing Miri home, there is only one reasonable thing to do: return Miri to her mother. But the girl\'s innocent laugh and pure worldview quickly enamor her to Kazuki, who secretly enjoys playing a parent, and it is not long before Rei\'s impenetrable heart makes room for Miri.\n\nMiri\'s every move is unpredictable, and Kazuki and Rei find raising an energetic child harder than any of their missions. Although it presents a great risk to their careers, Kazuki and Rei—both assuming the affectionate nickname \"papa\"—decide to provide Miri with a normal childhood despite all the odds stacked against them.\n\n[Written by MAL Rewrite]', 'https://cdn.myanimelist.net/images/anime/1183/132462.jpg', 'https://myanimelist.net/anime/53411/Buddy_Daddies', 53411),
(17, 'The Angel Next Door Spoils Me Rotten', 'Saturdays', 'Mahiru Shiina is worthy of her nickname \"Angel\": she is a divine beauty loved by all, and she excels in both academics and athletics. Shiina lives in an entirely different world from Amane Fujimiya, her next-door neighbor. Despite living so close together, they have never spoken once. But their silence is broken when Fujimiya spots Shiina gloomily sitting on a swing amidst a heavy rainstorm and lends her his umbrella. \n\nWhen Fujimiya catches a cold the next day, Shiina wishes to return the favor for the umbrella by nursing him back to health. Believing that this would be their first and last interaction, he silently appreciates her kindness. However, Shiina—who can not help but worry about Fujimiya\'s lack of tidiness and proper nutrition—begins to cook and clean for him. As the unlikely pair spend time together in Fujimiya\'s apartment, they explore the true nature of their relationship and the gentle emotions that emerge from it.\n\n[Written by MAL Rewrite]', 'https://cdn.myanimelist.net/images/anime/1758/133556.jpg', 'https://myanimelist.net/anime/50739/Otonari_no_Tenshi-sama_ni_Itsunomanika_Dame_Ningen_ni_Sareteita_Ken', 50739),
(18, 'Trigun Stampede', 'Saturdays', 'On the planet Noman\'s Land, reporters Meryl Stryfe and Roberto De Niro traverse the desert in search of the infamous outlaw Vash the Stampede. But the man they find near the desolate town of Jeneora Rock is a far cry from the lethal terrorist they expect. In reality, Vash is a passive and carefree drifter; he is a proponent of peace, beloved by the residents of the town. His inaccurate reputation actually stems from the widespread atrocities committed by his twin brother Knives Millions. Still, Vash is dubbed \"The Humanoid Typhoon\'\' due to the tendency for violent chaos to follow in his wake.\n\nChaos soon arrives in the form of bounty hunters seeking the high price on Vash\'s head, and their violent pursuit poses great danger to the town and its precious power plant. Thanks to his gunslinging prowess, Vash is able to resist most of these nefarious forces. Yet he must soon face off against the ultimate evil: the unstoppable destructive power of his malevolent brother.\n\n[Written by MAL Rewrite]', 'https://cdn.myanimelist.net/images/anime/1426/129194.jpg', 'https://myanimelist.net/anime/52093/Trigun_Stampede', 52093),
(19, 'The Reincarnation of the Strongest Exorcist in Another World', 'Saturdays', 'Despite standing at the zenith as the strongest exorcist, Haruyoshi Kuga sought even greater power, which led to his demise at the hands of those who envied his might. As he draws his last breath, he casts a spell that allows him to reincarnate and swears to become more cunning, hoping that all his efforts will prove useful in his next life.\n\nHaruyoshi is soon reborn in another world as Seika Lamprogue, an illegitimate son of a noble family that prides itself on magic. However, his new family largely ignores him due to his lineage and magic deficiency. Nevertheless, the unbothered Seika leverages the knowledge from his previous life to make numerous valuable allies. As he begins to explore the true limits of his abilities, Seika must also be wary of the consequences that tarnished his past and avoid repeating the same mistakes.\n\n[Written by MAL Rewrite]', 'https://cdn.myanimelist.net/images/anime/1547/125900.jpg', 'https://myanimelist.net/anime/50932/Saikyou_Onmyouji_no_Isekai_Tenseiki', 50932),
(20, 'My Life as Inukai-san\'s Dog.', 'Saturdays', 'On a rainy afternoon, a male high school student awakens freezing on the streets with no memory of how he got there. His classmate and crush, Karen Inukai, finds him and takes him back to her home where, to his surprise, she starts to undress. She seems intent on bathing with him, though he has no idea why. When she holds him once more, he catches a glimpse of himself in the mirror—discovering that he has turned into a dog!\n\nInukai adopts the puppy and names him Pochita. Now, he must adjust to life as a dog and figure out how to get out of this strange predicament. But while he mulls over an escape plan, Pochita sees a whole new side to Inukai that he never saw at school.\n\n[Written by MAL Rewrite]', 'https://cdn.myanimelist.net/images/anime/1832/132333.jpg', 'https://myanimelist.net/anime/51265/Inu_ni_Nattara_Suki_na_Hito_ni_Hirowareta', 51265),
(21, 'Is It Wrong to Try to Pick Up Girls in a Dungeon? IV Part 2', 'Saturdays', 'Second part of Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka IV.', 'https://cdn.myanimelist.net/images/anime/1226/131884.jpg', 'https://myanimelist.net/anime/53111/Dungeon_ni_Deai_wo_Motomeru_no_wa_Machigatteiru_Darou_ka_IV__Fuka_Shou_-_Yakusai-hen', 53111),
(22, 'The Misfit of Demon King Academy Ⅱ', 'Sundays', 'As peace returns to the demon realm, Anos Voldigoad wishes nothing more than to put his reputation as the Demon King of Tyranny to rest and go back to being a misfit at the prestigious Demon King Academy. Unfortunately, any tranquility is fleeting: sinister demons, kings, and deities plot Anos\'s demise from the shadows.\n\nRumors spread about the \"Child of God,\" a being whose power may rival that of Anos. To uncover the truth and eliminate the potential threat, Anos must journey deep into the land of spirits. However, the spirit world is shrouded in mystery, and it may only be entered after undergoing a series of difficult trials.\n\nWith unrivaled power and confidence, Anos braces himself to defeat various formidable enemies with grandiose titles. But he—with the assistance of his trusted allies—will barely have to break a sweat as the true Demon King of Tyranny.\n\n[Written by MAL Rewrite]', 'https://cdn.myanimelist.net/images/anime/1471/128323.jpg', 'https://myanimelist.net/anime/48417/Maou_Gakuin_no_Futekigousha__Shijou_Saikyou_no_Maou_no_Shiso_Tensei_shite_Shison-tachi_no_Gakkou_e_Kayou_II', 48417),
(23, 'NieR:Automata Ver1.1a', 'Sundays', 'The distant future, 5012.\n\nThe sudden aerial invasion of Earth by &lt; Aliens ＞ and their creations ＜Machine Lifeforms＞led mankind to the brink of extinction. The surviving number of humans who took refuge on the moon to organize a counterattack using ＜android＞ soldiers to recapture Earth.\n\nHowever, the war reaches a stalemate as the ＜Machine Lifeforms＞ continue to multiply infinitely. In turn, humanity deploys anew unit of android soldiers as an ultimate weapon: ＜YoRHa＞\n\nNewly dispatched to Earth ＜2B＞ joins＜9S＞, the analyst currently stationed there, where amid their mission, they encounter a myriad of mysterious phenomena...\n\nThis is the story of these lifeless ＜androids＞ and their endless fight for the sake of mankind.\n\n(Source: NieR:Automata Ver1.1a Official USA Website)', 'https://cdn.myanimelist.net/images/anime/1399/128318.jpg', 'https://myanimelist.net/anime/51105/NieR_Automata_Ver11a', 51105),
(24, 'Don\'t Toy with Me, Miss Nagatoro 2nd Attack', 'Sundays', 'Hayase Nagatoro and Naoto Hachiouji have grown closer: the girl spends more time than ever in the art club room with her senpai. Although he is always on edge, Naoto no longer seems to mind Nagatoro\'s presence. Time and again, Naoto demonstrates his hidden, cool demeanor, and Nagatoro displays her possessive tendencies. However, they still can not seem to completely close the distance between them. It is clear to everyone else that the pair have feelings for each other.\n\nFor Nagatoro, there is nothing more entertaining than toying with Naoto. But as the girl shows no plans to stop teasing her senpai, it is only a matter of time before they realize how they truly feel.\n\n[Written by MAL Rewrite]', 'https://cdn.myanimelist.net/images/anime/1902/129579.jpg', 'https://myanimelist.net/anime/50197/Ijiranaide_Nagatoro-san_2nd_Attack', 50197),
(25, 'Tokyo Revengers: Christmas Showdown', 'Sundays', 'In spite of his best time-leaping efforts, Takemichi Hanagaki continuously fails to prevent the present-day death of Hinata Tachibana, his adolescent love. The adult Takemichi grapples with grief and the ramifications of the Tokyo Manji gang\'s criminal empire—an unintended product of his timeline meddling. Though the gang once operated under the idealistic Manjirou \"Mikey\" Sano, it has now been taken over by the malicious Tetta Kisaki and, as a result, has abandoned its original optimistic intent.\n\nDespite feeling hopeless, Takemichi travels to the past once again to investigate Black Dragon, a rival motorcycle gang whose actions ultimately lead to Hinata\'s demise. There, he meets the young Hakkai Shiba, a fellow gang member whose older brother, Taiju, tyrannically rules Black Dragon. When Taiju brutally beats Takemichi in a one-sided street brawl, Hakkai attempts to withdraw from Tokyo Manji in apology—an act that Takemichi must prevent to spare Hakkai a grim future.\n\nThrough a shared tragedy, Takemichi bonds with Chifuyu Matsuno, establishing a close comradery both boys desperately need. With Chifuyu on his side, Takemichi works to unravel the fates of Black Dragon\'s members, fighting to create a happy future for his loved ones.\n\n[Written by MAL Rewrite]', 'https://cdn.myanimelist.net/images/anime/1773/132313.jpg', 'https://myanimelist.net/anime/50608/Tokyo_Revengers__Seiya_Kessen-hen', 50608);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `Anime`
--
ALTER TABLE `Anime`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `MalID` (`MalID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `Anime`
--
ALTER TABLE `Anime`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=51;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
